# Generated by Django 3.2 on 2021-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwi', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('perforation_obs_no', models.IntegerField()),
                ('completion_obs_no', models.IntegerField()),
                ('active_ind', models.CharField(max_length=50)),
                ('top_depth', models.IntegerField()),
                ('top_depth_uom', models.CharField(max_length=50)),
                ('top_tvd_depth', models.CharField(blank=True, max_length=50, null=True)),
                ('top_tvd_depth_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('base_depth', models.IntegerField()),
                ('base_depth_uom', models.CharField(max_length=50)),
                ('base_reservoir', models.CharField(blank=True, max_length=50, null=True)),
                ('base_tvd_depth', models.IntegerField(blank=True, null=True)),
                ('base_tvd_depth_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('top_strat_unit_id', models.CharField(max_length=50)),
                ('top_strat_age', models.IntegerField()),
                ('base_strat_unit_id', models.CharField(max_length=50)),
                ('base_strat_age', models.IntegerField()),
                ('perforation_date', models.DateField()),
                ('completion_source', models.CharField(blank=True, max_length=50, null=True)),
                ('completion_status', models.CharField(max_length=50)),
                ('perforation_angle', models.FloatField(blank=True, null=True)),
                ('completion_status_type', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status_date', models.DateField(blank=True, null=True)),
                ('perforation_ba_id', models.CharField(blank=True, max_length=50, null=True)),
                ('perforation_count', models.IntegerField()),
                ('perforation_interval_type', models.CharField(max_length=50)),
                ('perforation_density', models.CharField(blank=True, max_length=50, null=True)),
                ('perforation_diameter', models.FloatField()),
                ('perforation_diameter_uom', models.CharField(max_length=50)),
                ('perforation_method', models.CharField(max_length=50)),
                ('perforation_per_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('perforation_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('perforation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cluster_per_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('row_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('province_state', models.CharField(max_length=50)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_type', models.CharField(max_length=50)),
                ('charge_size', models.IntegerField(blank=True, null=True)),
                ('charge_size_uom', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_no', models.IntegerField()),
                ('row_changed_by', models.CharField(max_length=50)),
                ('row_changed_date', models.DateField()),
                ('row_created_by', models.CharField(max_length=50)),
                ('row_created_date', models.DateField()),
            ],
            options={
                'db_table': 'performance',
            },
        ),
    ]
