# Generated by Django 3.2 on 2021-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app1', '0002_performancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemodel',
            name='charge_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancemodel',
            name='completion_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancemodel',
            name='current_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancemodel',
            name='perforation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performancemodel',
            name='row_changed_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performancemodel',
            name='row_created_date',
            field=models.DateTimeField(),
        ),
    ]
